### PR TITLE
BVTCK-162 Test that ValueExtractor#extractValues() are correctly wrapped

### PR DESCRIPTION
**Pull request by gsmet**
* https://hibernate.atlassian.net/browse/BVTCK-162

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@gsmet I was wondering, do we mandate wrapping into `ValidationException` actually? Should I add something to the spec?

**Comment by gsmet** [comment]
See this commit: https://github.com/beanvalidation/beanvalidation-spec/pull/206/commits/561e4dcaf4ad069023636ff78d0dfb8e6b9f3585

It was already mandated for all the other extension points and we added `ValueExtractor` in this commit.

**Comment by gunnarmorling** [comment]
Ah, I see. I didn't find it because I was looking for this in a different place. I've just filed https://github.com/beanvalidation/beanvalidation-spec/pull/220 for that (we follow that same pattern for other wrapped exceptions). Can you merge that one first, then update the `@SpecAssert` to refer to that new assertion, too. Thanks!

**Comment by gsmet** [comment]
@gunnarmorling done!

**Comment by gunnarmorling** [comment]
And merged. Thanks, @gsmet!

**Pull request merged**
