### PR TITLE
Update jboss-test-audit version and remove some @SpecAssertions annot…

### PR DESCRIPTION
**Pull request by tremes**
…ations.

### CODE REVIEW

**Comment by gsmet** [comment]
ok to test

**Comment by gsmet** [comment]
@tremes merged, thanks! And a big thanks for taking the time to remove the annotations.

**Comment by tremes** [comment]
Np. There are still some...I can open new PR later.

**Comment by gsmet** [comment]
I think we will change them along the road. No biggie!

**Pull request closed without merging**
